"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _committees_grid from './committees-grid.bones.json'
import _officers_list from './officers-list.bones.json'
import _committee_banner from './committee-banner.bones.json'
import _committee_content from './committee-content.bones.json'
import _committee_sidebar from './committee-sidebar.bones.json'

registerBones({
  "committees-grid": _committees_grid,
  "officers-list": _officers_list,
  "committee-banner": _committee_banner,
  "committee-content": _committee_content,
  "committee-sidebar": _committee_sidebar,
})
